package com.ruleengine.idlpre;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class offsetvalue implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.math.BigDecimal offsetInt;
	private java.lang.String product_id;

	public offsetvalue() {
	}

	public java.math.BigDecimal getOffsetInt() {
		return this.offsetInt;
	}

	public void setOffsetInt(java.math.BigDecimal offsetInt) {
		this.offsetInt = offsetInt;
	}

	public java.lang.String getProduct_id() {
		return this.product_id;
	}

	public void setProduct_id(java.lang.String product_id) {
		this.product_id = product_id;
	}

	public offsetvalue(java.math.BigDecimal offsetInt,
			java.lang.String product_id) {
		this.offsetInt = offsetInt;
		this.product_id = product_id;
	}

}